# Application Config
server:
  port: 8088

spring:
  application:
    name: API-Gateway

# Eureka Config
eureka:
  client:
  serviceUrl:
    defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

#Managing the logging
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

  #logging.level.root=INFO
  com.eresh.spring: INFO

  file: ${sys:logs}/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm} %-5level %logger{36} -%M -%msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %M - %msg%n"

ribbon:
  eager-load:
    enabled: true

  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  ignored-services: '*'
  routes:
    product:
      path: /product/**
      service-id: product-service
